name: Publish to Github Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - uses: actions/checkout@v4

      - name: deps
        run: yarn install --frozen-lockfile

      - name: lint
        run: yarn lint

      - name: build
        run: yarn run build

      - name: upload
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
